import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
	id 'maven-publish'
	id 'org.jetbrains.kotlin.jvm' version "2.3.10"
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

base {
    archivesName = project.archives_base_name
}
version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
	mavenLocal()
	maven {
		url = "https://maven.nucleoid.xyz"
	}
	maven {
		url = "https://oss.sonatype.org/content/repositories/snapshots"
	}
	maven {
		url = "https://maven.potato.garden/releases"
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Yes this has to be capitalised
	implementation "com.github.quiltservertools:Ledger:1.3.20"

	implementation "net.fabricmc:fabric-language-kotlin:1.13.9+kotlin.2.3.10"

	implementation("com.uchuhimo:konf-core:1.1.2")
	implementation(include("com.zaxxer:HikariCP:7.0.2"))

	// H2
	implementation(include("com.h2database:h2:2.4.240"))

	// MySQL
	implementation(include('com.mysql:mysql-connector-j:9.6.0'))

	// MariaDB
	implementation(include('org.mariadb.jdbc:mariadb-java-client:3.5.7'))

	// PostgreSQL
	implementation(include("org.postgresql:postgresql:42.7.9"))
	
	//SQLite
	implementation('org.xerial:sqlite-jdbc:3.50.3.0')

	implementation("me.lucko:fabric-permissions-api:0.7.0")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"

	it.options.release = 25
}

tasks.withType(KotlinCompile).configureEach {
    it.compilerOptions.jvmTarget = JvmTarget.JVM_25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}"}
	}
}
